### ISSUE TITLE
Attempt open using UIApplication openURL

### ISSUE THREAD

**Issue by radj** [conradev/Open#6]
I forked the code and tried to use `UIApplication`'s `openURL:` if it fails with `SBSLaunchApplicationWithIdentifier()`. It still doesn't work but calling `openURL:` from within an app is fine. Any idea why this is?

Ex: Running `open http://www.apple.com` should open the default browser. It fails when calling `openURL` on this URL from inside Open but it works fine when calling `openURL` from inside an app.

**Comment by conradev** [comment]
That is because there is no `UIApplication` inside `open`. `[UIApplication sharedApplication]` is `nil`. Instead, use this:

`[[LSApplicationWorkspace defaultWorkspace] openApplicationWithBundleID:]`

**Comment by radj** [comment]
Makes sense! Thanks for pointing me to `LSapplicationWorkspace`. It has `openURL`, too!
